const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ success: true, data: [] });
});

router.post('/update', (req, res) => {
  res.json({ success: true, message: 'Keys updated' });
});

router.get('/export/softcam', (req, res) => {
  res.set('Content-Type', 'text/plain');
  res.send('# SoftCam.Key\n# Generated by SatGuard Pro\n');
});

module.exports = router;
